gobuffalo/pop

mysql.go
mysql_test.go

Preserve user specific URL options while running `buffalo db create` and `buffalo db drop`.

preserve user specific URL options while 'db create' and 'db drop'.

---

.goreleaser.yml
Gopkg.lock
README.md
config.go
config_test.go
database.yml
pop.go
pop_test.go
soda/cmd/generate/attribute_test.go
soda/cmd/generate/config_cmd.go
soda/cmd/generate/model.go
soda/cmd/version.go
sqlite.go
sqlite_shim.go
test.sh

@markbates I just worked on eager loading nested associations. 
The overall idea is  adding to pop the ability to eager loading nested associations. To give you an example of how it would be used, take a look at the code below:
```go
type User struct {
ID           uuid.UUID   `db:"id"` 
FavoriteSong Song        `has_one:"song"`
Books        Books       `has_many:"books"`
}
type Song struct {
ID          uuid.UUID    `db:"id"`
UserID      uuid.UUID    `db:"user_id"`
Title       string       `db:"title"`
}
type Book struct {
ID       uuid.UUID  `db:"id"`
UserID   uuid.UUID  `db:"user_id"`
User     User       `belongs_to:"user"`
Writers  Writers    `has_many:"writers"`
}
type Writer struct {
ID     uuid.UUID   `db:"id"`
Name   string      `db:"name"``
BookID uuid.UUID   `db:"book_id"`
Book …
```

Inner associations Eager Loading

---

associations/belongs_to_association.go
associations/belongs_to_association_test.go
finders_test.go
migrations/20160808213310_setup_tests2.up.fizz
pop_test.go

@markbates @larrymjordan @macrael This is a follow-up PR to [this issue](https://github.com/markbates/pop/issues/199) from the markbates repo.
This PR changes the behavior of `belongsTo` such that the ID field for `Foo fooType` is mapped to `FooID` instead of `FooTypeID`. This allows you to use `belongsTo` with multiple fields of the same type without the ID fields colliding with each other. This also jibes well with the [Rails](http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-foreign-key) implementation of this relationship.

BelongsTo uses field name instead of type for ID field

---

fizz/translators/postgres.go

Previously fizz would not allow you to use `bigint` as a primary key type; this commit adds support using `bigserial` as the backing type.
Replaces PR #17.

fizz/translators: support bigint primary keys in postgres

---

scopes.go

*Note: I'm happy to put this example somewhere else if it's too cumbersome to have in the source instead of a README or guide or wherever.*
* Add more to the in-line example for `connection.Scope` to show using two `ScopeFunc`s at once
* Fix a typo (missing parens) in the `query.Scope` example
Just to make it a bit more obvious for the next docs reader 😄

Expand Scope example to show chaining

---

postgresql.go

See: https://github.com/gobuffalo/buffalo/issues/836
If the db is not precised, postgresql takes the username as the database to connect on.
To avoid a connection problem if the user db is not here, we use the default "postgres"
db, just like the other client tools do.

Fix issue with postgresql urlWithoutDb

---

fizz/bubbler.go

The package currently does not build because `github.com/mattn/anko/builtins` is renamed to `core`. This fixes the building.
The breakage is detected by smallrepo.com
See https://smallrepo.com/builds/20180318-152003-ee90cabc for more details.

Fix import in fizz.

---

cockroach.go
dialect.go
file_migrator.go
migration_box.go
migration_box_test.go
migration_info.go
migrator.go
mysql.go
pop.go
postgresql.go
sqlite.go

This PR allows Pop users to target a specific database, when using migrations. It uses a suffix for each supported database, in the form of `dbtype.(up|down).sql`.
Example: `20180413210602_create_users.mysql.up.sql` targets a MySQL database, but `20180413210602_create_users.postgres.up.sql` targets a PostgreSQL one.
To ensure back-compatibility with the current norm, non-suffixed migrations are considered safe for every database, and are taken in account for each supported dialect.

Allow migrations to target a specific database

---

README.md
soda/cmd/generate/model.go
soda/cmd/generate/model_cmd.go

Enables to choose the type of migration file you want during the model generation with flag ```--migration-type string```

add flag to choose the type of migration file

---

README.md
connection.go
connection_details.go
migrator.go
schema_migrations.go
schema_migrations_appengine.go

Enables changing the default migration table name ("schema_migrations")

Add migration table name option

---

migrator.go

The new configurable migration table feature introduced typos in migration SQL entries.
Fixes #64.

Fix a regression with migrations

---

fizz/bubbler_test.go
fizz/fizz.go

This is a fix for https://github.com/gobuffalo/pop/issues/54
Anko doesn't seem to care if a function returns an error value, so the error returned by `Exec()` was being ignored. The most reasonable way to address this was to add a `panic`, similar to how [`add`](https://github.com/gobuffalo/pop/blob/master/fizz/fizz.go#L20) does.

Fixing ignored errors from fizz `exec()`

---

README.md

the tag is needed to install with sqlite support, with out it you get cryptic failures like...
```
[POP] 2018/05/13 15:13:37 Loading config file from %!s(MISSING)
| ["/Users/jtang/sandbox/pop/database.yml"]
```

Add tag flag to command

---

migrations/20160808213310_setup_tests2.up.fizz
mysql.go

* Use SET SESSION FOREIGN_KEY_CHECKS to disable / enable fks.
* Fix MySQL truncation list to exclude views.

Fix #49: disable MySQL foreign keys on truncate all

---

connection.go
postgresql.go
soda/cmd/schema/load.go

This PR replaces the call to `psql` to load a schema from a file with the equivalent in Go, for the postgresql driver.
This is an adaptation from [sqlx `LoadFile`](https://github.com/jmoiron/sqlx/blob/2aeb6a910c2b94f2d5eb53d9895d80e27264ec41/sqlx.go#L702).

[Postgres] LoadSchema using Go instead of psql tool

---

finders.go

This change makes use of the SQL `EXISTS` statement, so the DB doesn't need to count all the rows to check existence.

Replace SQL COUNT call for Exists with SQL EXISTS

---

Gopkg.lock

The Gopkg.lock is broken if you use it with dep without an automatic update:
```
$ git clone https://github.com/gobuffalo/pop
Cloning into 'pop'...
remote: Counting objects: 5500, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 5500 (delta 6), reused 12 (delta 5), pack-reused 5481
Receiving objects: 100% (5500/5500), 4.47 MiB | 13.12 MiB/s, done.
Resolving deltas: 100% (3129/3129), done.
$ cd pop
$ dep ensure -vendor-only
$ go build
fizz/bubbler.go:31:30: cannot use "github.com/gobuffalo/pop/vendor/github.com/mattn/anko/vm".NewEnv() (type *"github.com/gobuffalo/pop/vendor/github.com/mattn/anko/vm".Env) as type *"github.com/mattn/anko/vm".Env in argument to core.Import
$
```
This CL fixes the Gopkg.lock:
```
$ dep ensure
$ go build
$
```
Fixes #109.
Fixes #110. …

pop: update Gopkg.lock

---

Gopkg.lock
migrator.go

Currently, Soda will consider any file that contains some sequence-stamped alphanumeric string, followed by `.up` or `.down`, followed by `.sql` or `.fizz`, as eligible for migration. While this narrows the search considerably, it doesn't account for files that contain `.sql` and `.fizz`—and otherwise match the pattern defined in mrx—but end in some _other_ file suffix.
For example, if you were to edit one of these migration files with Vim, you may have a file in the form of `.12345-whatever.up.sql.swp`. Soda will attempt to migrate this, but fail, for several reasons (besides the duplication of SQL logic, `swp` files contain Vim artifacts which Soda will not expect).
I propose here that files to be migrated _must end_ in either `.sql` or `.fizz`, not merely contain them.
One may …

Require that file names end in .sql or .fizz

---

README.md

The ActiveRecord link was using the wrong markdown syntax, so the markup for it looked like `(ActiveRecord)[...link to Rails docs...]`. We just need to use square brackets for `ActiveRecord` and parens for the link, and all should become well.

Flip brackets and parens on ActiveRecord link

---

Gopkg.lock
go.mod
soda/cmd/schema/dump.go
soda/cmd/schema/load.go

* Fix default values for schema subcommands, so it's dumped and read from
the same default location.
* schema subcommands now use the same value for env as the root one.

Fix #66: Double schema.sql and different env behavior

---

.travis.yml
connection_details.go
database.yml
finders_test.go
mysql.go
soda/cmd/generate/config_templates.go

* Keep the default encoding to "utf8_general_ci" to not break current setups.
* Generate the templates with the "utf8mb4_general_ci" encoding, for new apps.
* New "encoding" param to set the encoding for DB creation & connection.

Fix #21: Handle encoding for MySQL

---

migrator.go

This prevents pop to grap temp/backup files. Fixes #151.

Fix #151: ensure the migration file name starts with a number

---

soda/cmd/generate/model.go

Even if the issue is written as closed: https://github.com/gobuffalo/pop/issues/156, a closing parenthesis at the end of the fizz file was showing the warning about old style fizz.

Small Fix for issue #156

---

postgresql.go

As discussed in Slack if you have multiple schemas TruncateAll is only truncating tables in `public` schema, this change truncates the rest of the schema tables as well.

Changes pgTruncate to Truncate all schemas

---

migrations/20160808213308_setup_tests.up.fizz
migrations/20160808213310_setup_tests2.up.fizz

Since fizz is not adding the ID column by itself anymore, we have to change the test migrations a bit.
THis change doesn't affect users, since soda/buffalo db already generated the ID for users.

Fix test fizz migrations to include an ID

---

fix/anko.go
fix/fixtures/pass/0001_with_raw_backticks.anko.fizz
soda/cmd/generate/model_test.go

Fix Anko converter

---

associations/many_to_many_association.go
associations/many_to_many_association_test.go

The referencing column name can be set using the primary_id tag in the struct.
The reason for this change is that I have two structs that read from the same DB column that have different concerns.

Added primary_id functionality to the many to many relationship 

---

soda/cmd/generate/attribute.go
soda/cmd/generate/attribute_test.go
soda/cmd/generate/model.go
soda/cmd/generate/model_cmd.go
soda/cmd/generate/model_test.go

* Extract duplicates validation from Model cmd
* Validate the attribute name is a valid Go name
Related to https://github.com/gobuffalo/buffalo/issues/870

Improve model attributes validation

---

config.go
connection.go
connection_details.go
logging/const.go
sqlite_shim.go

This PR will help to troubleshoot configuration file errors:
* Add an Error level for the logger.
* Log config file loading errors.
* Prevent a bad connection declaration to abort Connections parsing.

Improve bad configuration file errors reporting

---

soda/cmd/migrate.go
soda/cmd/root.go

`db migrate excans up` shouldn't work.

Prevent migrate command to take any argument

---

soda/cmd/generate/attribute.go
soda/cmd/generate/attribute_test.go
soda/cmd/generate/model.go
soda/cmd/generate/model_cmd.go
soda/cmd/generate/model_test.go

* Prevent global vars usage.
* Move struct tag check in model constructor.

Refactor model cmd config

---

soda/cmd/drop.go

Drop command shouldn't need a confirmation, but we should help to prevent bad mistakes.

Revert breaking change introduced by #235

---

bench.sh
executors.go
finders.go
sql_builder.go

* Fix bench.
* Use `whereID` when possible.
* Change `columnCacheMutex` to a `RWMutex` (read ops should be greater than write ops, or the cache means noting).

Add minor changes

---

soda/cmd/generate/attribute.go
soda/cmd/generate/attribute_test.go
soda/cmd/generate/model_templates.go

When trying to figure out why https://github.com/gobuffalo/buffalo/pull/1346 was failing I found that the model template is producing a broken model.  
```bash
$ soda g model user name
```
```go
func (u *User) Validate(tx *pop.Connection) (*validate.Errors, error) {
return validate.Validate(
&validators.StringIsPresent{Field: u.Name, Name: "Name"},
), nil
}
```
```go
func (u *User) Validate(tx *pop.Connection) (*validate.Errors, error) {
return validate.Validate(
&validators.StringIsPresent{Field: u.name, Name: "name"},
), nil
}
```

fixes broken model template

---

query_test.go
sql_builder.go

This PR allows to pass an slice for `In` even when using multiple wildcards in `Where` calls. This is related with an old issue reported in https://github.com/markbates/pop/issues/123

Query in support with slice args.

---

config.go

Soda already call it on RootCmd, it can be called by the user, and Connect already calls it.

Remove LoadConfigFile on lib init

---

connection_details.go
connection_details_test.go
dialect_cockroach.go
dialect_mysql.go
dialect_mysql_test.go
dialect_postgresql.go
dialect_sqlite.go
pop.go

Hi all,
I proposed #281 and I have no responses yet. Anyway, I tried to change some basic things to remove database engine specific stuff from connection details.
By this change, now:
* added two global maps for database specific URL parsers and finalizers.
* when `init()` for dialect was executed, it register database specific parser and finalizer if exist.
* original parser was rename to `withURL()` from `overrideWithURL()`.
* original parser does generic URL parsing and calling database specific parser.
* database specific parser does special URL handling for its driver/behavior.
* original finalizer in connection details controls the flow and call database specific finalizer.
* database specific finalizer does set default values, makes a database specific warnings,...
* all `switch`s …

connection details cleanup

---

connection_details_test.go
database.yml
dialect_mysql.go
dialect_mysql_test.go

With this PR and previously merged PR, all hardcoded options for MySQL dialect are removed and it can be configured with `options` in `database.yml`. For example,
```yaml
development:
dialect: mysql
options:
collation: utf8mb4_general_ci
readTimeout: 1s
parseTime: true
multiStatements: true
```
Previously,
* `collation`: was configured with `encoding` key (high level key but only used by MySQL)
* `readTimeout`: was hardcoded for generated URL and changed from time to time.
* `parseTime` and `multiStatements`: was hardcoded for generated URL.
For `encoding` configuration, deprecated message was added to notice users.
There are some minor bugfixes related to these changes and added some test cases to cover most of the codes.
(related to #281)

fixed mysql dialect to use `options` instead of `encoding` and hardcoded values

---

schema_migrations.go
schema_migrations_appengine.go

This will prevent big indexes for nothing.

Fix version field size in migrations table

---

associations/belongs_to_association.go
executors_test.go
migrations/20181130023854_head_ptr.down.fizz
migrations/20181130023854_head_ptr.up.fizz
pop_test.go

Fixes a couple panics when working with pointers and beforeSave associations:
- The first was calling `Elem()` on a nil pointer, which returns a zero value that `Interface()` later panics on
- The second panic occurs when `BeforeSetup` attempts to set a pointer-type associated ID field

Fixes beforeSave pointer panics

---

connection.go
connection_test.go
dialect.go
dialect_cockroach.go
dialect_mysql.go
dialect_postgresql.go
dialect_sqlite.go

Added callback function `afterOpen()` to interface `dialect` and call it from `Connection.Open()` to handle dialect specific initial setup. (as first part of proposal #295)
With this, I hope we can give dialect a change to prepare its own settings include getting server information which I already added to dialect for CockroachDB. I think it can help us to handle version different of the same database engine and service variations. (with the information from the connected server.)
Before I adding this, I made a small change to `connection.go` to prevent panic on the badly configured connection.
Please check this PR.

Improving connection

---

belongs_to.go
soda/cmd/drop.go
soda/cmd/root.go
soda/main.go

Usage is still supported, but won't show on every error.

Silence usage on error

---

migrations/20181104135255_users.up.fizz
migrations/20181104135526_good_friends.up.fizz
migrations/20181104135627_validatable_cars.up.fizz
migrations/20181104135710_not_validatable_cars.up.fizz
migrations/20181104135800_callbacks_users.up.fizz
migrations/20181104135829_books.up.fizz
migrations/20181104135856_taxis.up.fizz
migrations/20181104140055_songs.up.fizz
migrations/20181104140142_composers.up.fizz
migrations/20181104140221_writers.up.fizz
migrations/20181104140340_addresses.up.fizz
migrations/20181104140431_users_addresses.up.fizz
migrations/20181104140522_courses.up.fizz
migrations/20181104140606_course_codes.up.fizz
migrations/20181104140743_cakes.up.fizz
migrations/20190219210052_students.up.fizz
migrations/20190219210059_parents.up.fizz
soda/cmd/generate/model.go
soda/cmd/generate/model_test.go

Related to #155. This still needs a proper change to the fix command.

Add Timestamps() macro when generating fizz migrations

---

connection.go
connection_details.go

The zero value was not the same as in the stdlib and could cause
perfs issues. This will now not call SetMaxIdleConns when IdlePool
is set to the zero value.
Fixes #376

Fix IdlePool option

---

genny/config/templates/mysql.yml.tmpl

由于MySQL并不支持 encoding 属性
所以修改为 collation 以获得正确的结果

修改 encoding 属性为 collation

---

config_test.go
file_migrator.go
migration_box.go
migration_content.go

This PR externalizes the logic in migration runners and the `migrationContent` function.  MigrationContent is now a public function with a flag to disable templating.  This PR simplifies the `findMigrations` functions so they can be overwritten more easily.

Migration runner and MigrationContent functions

---

model.go
model_test.go

For testing purposes there are situations where I'd like to be able to specify the value of the `CreatedAt` field instead of setting it to the current time. This PR updates the `touchCreatedAt` method to only set the field if it has a zero value.

Allow for manually setting the CreatedAt field.

---

model.go
soda/cmd/generate/model_templates.go

When you update a model, the `updated_at` field contains nanoseconds. But these nanoseconds are not stored in the database. So when you fetch the model again from the database does not contain the nanoseconds. This can lead to weird situations for clients. 
For example, a iOS app sends a PUT request to update a certain model and stores the result. The `updated_at` field is `2019-07-20T10:36:19.819375Z`. Later, when re-fetching the result from the API it returns a different response (because the `updated_at` field is now `2019-07-20T10:36:19Z`). This leads to weird situations. Also, Swift doesn't understand the nanoseconds.
PS: I couldn't find a better way to remove the nanoseconds.

Remove nanoseconds when touching updated at

---

connection.go
connection_details.go

I'd like to be able to set the maximum lifetime on a DB connection. My use case is that I'm authenticating to the DB using AWS IAM roles which have tokens that expire every 15 minutes. So my connection shouldn't last longer that that time before I need to generate a new token and a new connection. 
I am writing this PR because I can't seem to do this and it seemed easier to contribute back: 
```go
if db, ok := connection.Store.(*pop.dB); ok {
sqlxDB := db.DB
sqlxDB.SetConnMaxLifetime(10 * time.Minute)
}
```

Allow setting connection max lifetime

---

columns/columns.go
columns/columns_test.go

Resolves #429
Adds a `colNames` function that returns a `[]string` sorted. This allows the column names to be modified before being strung together, while ensuring that weird quirks don't cause them to be sorted in a different way. For example: `"a" < "a_" < "a``"`

Fixed column order

---

.goreleaser.yml
.goreleaser.yml.plush

Goreleaser now requires IDs for distinct builds.
Also improve the brew formula to be aware of beta releases.

 Upgrade goreleaser config

---

dialect_cockroach.go

TruncateAll() func in PostgreSQL dialect doesn't truncate the migration table so I think CockroachDB shouldn't truncate it either. 
I was using PostgreSQL previously and I used TruncateAll() in my `db:seed` task. With CockroachDB the same `db:seed` task messes up the database migrations in development environments.

Prevent CockroachDB TruncateAll from emptying the migration table

---

dialect_common.go
dialect_postgresql_test.go

Problem
Update and Delete are not working with tables name that have schema ("schema.table_name")
Behavior
Actual:
```sql
UPDATE "schema.table_name" SET...
```
Generate psql error
Expected:
```sql
UPDATE "schema"."table_name" SET...
```
DB used to test:
PostgreSQL 9.6

Fix escape quote function

---

callbacks.go
callbacks_test.go
executors.go
migrations/20181104135800_callbacks_users.up.fizz
pop_test.go

Add a callback to be run prior to validation.
Existing callbacks are all run after validation, so callback based changes to models can't be included in validation.
Example use case:
Password hashing in BeforeValidate, allowing validation to be run on it to make sure it is present on a user.

Add callback before validate

---

executors.go
executors_test.go

In the documentation it states that `UpdateColumns()` updates the `updated_at` field automatically. This is slightly confusing because apparently you still need to include `updated_at` as a parameter for the function. This commit tries to clarify the ambiguity and also adds a test for `updated_at` field

Improve tests and documentation for UpdateColumns function

---

.gitignore
connection.go
connection_details_test.go
db.go
dialect_cockroach_test.go
store.go
tx.go

The implementation may work, but I haven't been able to test it and won't for some time. It does compile and existing tests still work (last I checked before merging development in).
If someone would like to verify this works, this could get merged in.
Additionally it would probably be beneficial to add this to the middleware in Buffalo to append the context on the tx in the context.
This PR is a rebased version of #472.

Add context.Context

---

dialect_cockroach.go
dialect_cockroach_test.go

Before this patch, when using a raw URL connection string such as
`crdb://foo/baz`, the cockroach dialect would not replace it with
`postgres://`. This causes an issue where the `lib/pq` driver
completely ignores the URL and simply falls back to the defaults
(localhost, 5432).
This patch changes that, by replacing `cockroach` (and aliases)
with `postgres` when returning the URL.

Cockroach URL scheme is now postgres

---

dialect_sqlite.go
dialect_sqlite_test.go

Trying to create an existing SQLite DB will now produce an error.
Fixes #501.

Align SQLite CreateDB behavior on other drivers

---

store.go

Expand variadic args in contextStore

---

dialect_mysql.go

Default charset was missing in create db statement. 
A version of [tidb](https://github.com/pingcap/tidb) we use does not accept using collate without charset. I think this change also made create  table statement complete in terms of using all options from connection config.

add charset to create table statement

---

migration_info.go
migration_info_test.go

fix: enforce precedence for specific migrations

---

migrator.go

`CreateSchemaMigrations` is not dependent on the migrator so it can easily be exposed as `pop.CreateSchemaMigrations`.
For backwards compatibility there is still the receiver version of the function.
The concrete use case was that I am moving from a different migration system and therefore I have to translate all the migration tables. This PR provides a safe way to create the pop migrations table.
I can also document this change but that would have to be in a different repo right?

feat: make CreateSchemaMigrations independent of the migrator

---

dialect_mysql.go

Bring dialect mysql on par with postgres and cockroachDB.
See: gobuffalo/pop#443

Prevent TruncateAll from emptying the migration table

---

migrator.go

Because `errors.Wrapf()` returns nil when `err` is nil, `!exist` would return nil despite it being an error state. This patch fixes addresses the issue by returning an error explicitly.

Return error when migration version does not exist

---

migration_info.go
migrator.go
packrd/packed-packr.go

Previously `Migrator.Down()` would run incompatible migrations. This patch addresses that issue by checking if the migration is compatible with the current translator/database before applying it.

Only run compatible down migrations

---

dialect_cockroach.go
dialect_common.go
dialect_postgresql.go

Previously, errors happening in prepared statements would be overshadowed by the statement close error. The `database/sql` documentation actually recommends using `statement.Close()` without error checking: https://golang.org/pkg/database/sql/#example_DB_Prepare
This patch addresses the issue which would cause the generic error message "current transaction is aborted, commands ignored until end of transaction block" when using prepared statements by properly wrapping errors.

Return original error when closing prepared statement

---

connection.go

Previously, errors happening in `Commit` or `Rollback` would always be overwritten by the inner error. For certain drivers this would obfuscate the reason for the error and return a generic: "current transaction is aborted, commands ignored until end of transaction block".
This patch fixes the flawed error handling logic and properly returns the error's root cause (e.g. FK violation).

Stop obfuscating transaction error

---

dialect_cockroach.go
dialect_common.go
dialect_postgresql.go
dialect_sqlite.go
finders.go
finders_test.go
model.go
pop_test.go
test.sh
testdata/migrations/20200621140800_clients.down.fizz
testdata/migrations/20200621140800_clients.up.fizz

Instead of optimistically guessing that the ID of a model is an int when the ID field is not defined, this patch now explicitly returns an error. This resolves several edgecase scenarios and closes #565

fix: return error when ID field is missing

---

go.mod
go.sum

In order to bump the SQLite dependency to the newest version, a replace is required to work around go-sqlite3's broken v2 release.

Bump go-sqlite3 to latest version

---

db.go
store.go
tx.go

This adds a new function that allows creating a transaction with `sql.TxOptions`.

feat: allow passing options to a new transaction

---

slices/map.go
slices/map_test.go

Fixes #417
Ensure uninitialized map is initialized when unmarshaling json
Add tests for this scenario

Ensure uninitialized map is initialized when unmarshaling json

---

pop_test.go
preload_associations.go
preload_associations_test.go
testdata/migrations/20181104135856_taxis.up.fizz

This PR solves the first issue mentioned in #547 -- the associated model fails to load when doing a `EagerPreload` on a `belongs_to` association where the FK field is a pointer.  Using `Eager`, the association had been loading fine.
It appears that the second issue mentioned in #547 has already been fixed in PR #589.

Add support for pointer FKs when preloading a belongs_to association

---

belongs_to.go
belongs_to_test.go
connection.go
connection_details.go
connection_instrumented.go
connection_instrumented_nosqlite_test.go
connection_instrumented_test.go
dialect_sqlite.go
executors.go
finders.go
finders_test.go
match_test.go
migration_info_test.go
model.go
model_context_test.go
model_test.go
preload_associations.go
query_test.go
scopes_test.go
soda/cmd/migrate_status.go
store.go
testdata/migrations/20210104145901_context_tables.down.fizz
testdata/migrations/20210104145901_context_tables.up.fizz
testdata/models/ac/user.go
testdata/models/bc/user.go
validations.go

This patch adds a feature which enables pop to pass down the connection context to the model's `TableName()` function by implementing `TableName(ctx context.Context) string`. The context can be used to dynamically generate tablenames which can be important for prefixed or generic tables and other use cases.

feat: support context-aware tablenames

---

.goreleaser.yml

It seems Goreleaser yml has changed for the action we use. This PR changes our iml to meet the expected syntax and  have our releases back to work.

Fixing Goreleaser

---

.github/workflows/tests.yml
dialect_cockroach.go
dialect_common.go
dialect_mysql.go
dialect_postgresql.go
docker-compose.yml
model.go
model_context_test.go
sql_builder.go
testdata/migrations/20210104145901_context_tables.up.fizz

This PR resolves issues around UPDATE and DELETE statements when table schemas are used in CRDB/PostgreSQL.
Also tests have been added to avoid future regressions.

Resolve issues in UPDATE and DELETE when using schemas

---

.github/workflows/release.yml
.github/workflows/tests.yml
connection.go
connection_details.go
go.mod

This PR add the possibility to configure the connection maximum idle time (https://golang.org/pkg/database/sql/#DB.SetConnMaxIdleTime).
More information on the associated issue
Close #632
Edit: I hadn't noticed but pop is targeting go1.13 however my changes require at least go1.15 (which is why the tests fail). I'm not sure what's the best strategy here, I could add a build constraint but it would require to duplicate the code.

Added connection maximum idle time configuration

---

pop_test.go
preload_associations.go
preload_associations_test.go

This PR attempts to fix #646 where `EagerPreload` does not load a `has_many` association with a pointer-based foreign key, but `Eager` works fine with the same association/pointer.

EagerPreload: Added fix/tests for has_many with pointer foreign key

---

dialect_cockroach.go
dialect_common.go
dialect_postgresql.go
dialect_sqlite.go

Some SQL logs were missing the values as argument. This adds the SQL arguments to the ones missing yet.

fix: log model values everywhere

---

dialect.go
dialect_cockroach.go
dialect_common.go
dialect_mysql.go
dialect_postgresql.go
dialect_sqlite.go
docker-compose.yml
executors.go
executors_test.go
query.go
sql_builder.go
test.sh

This allows writing delete queries without knowing the exact primary key or for composite keys.
`Destroy` only allows to delete by primary key, but there are many cases where you want to delete multiple rows or by some other query than the ID.
Contributes to #29

feat: add query.Delete

---

file_migrator.go
migration_box.go
migration_box_test.go
migration_info.go
migration_info_test.go
migrator.go

This is related to #533.
Basically, just reversing the up migration order does not work, as that puts "all" migrations before specific ones. Therefore, I added implemented the proper `Less` function for down migrations explicitly.

fix: sorting of down migrations

---

executors.go
pop_test.go

fix: preserve eager information when validating models (#664)

---

genny/model/templates/path-/name-.go.tmpl
go.mod
go.sum
soda/cmd/root.go
soda/cmd/version.go

Currently, the version printed by `buffalo-pop` (or `soda`) is still `v5.3.1`. It could make confusion.

updated version string and go.mod

---

soda/cmd/generate/model_cmd.go

Format generated `model.go` file and run `go mod tidy` for the file.
Implemented mod tidy with genny's runner since `genny/gogen/gomods` was removed in genny/v2.
updates: https://github.com/gobuffalo/cli/issues/65

hotfix: format generated file and mod tidy for them.

---

dialect_cockroach.go
soda/cmd/migrate.go

The  command has been removed from the CLI. This patch introduces a new mechanism to reliably dump the SQL schema for CockroachDB.

Replace removed  command

---

associations/associations_for_struct.go
columns/columns_for_struct.go
executors_test.go
pop_test.go
test.sh
testdata/migrations/20220214113659_embedded_struct.down.fizz
testdata/migrations/20220214113659_embedded_struct.up.fizz

Currently, embedded structs are not flattened during model column generation. The underlying libraries (reflect and sqlx) however support it already. Therefore, the change was not huge.
Please point me where to add more tests if needed.
closes #582

feat: support embedded struct fields

---

associations/associations_for_struct.go
docker-compose.yml
executors_test.go

This fixes some edge cases not covered in #691. Before these changes, associations in embedded structs would cause all kinds of panics in `reflect`.

fix: associations for embedded fields

---

dialect.go
dialect_cockroach.go
dialect_common.go
dialect_mysql.go
dialect_postgresql.go
dialect_sqlite.go
executors.go
executors_test.go
pop_test.go

This commit introduces a new function, UpdateQuery, that enables updating all
rows matched by a query. It can be used for conditional updates.

feat: implement UpdateQuery

---

executors_test.go
model.go

Provide a way to override the time used for CreatedAt/UpdatedAt. This can be really useful to make tests deterministic, but also for overriding things like the time zone for UpdatedAt
Resolves #591

feat: Allow customizing the time used for CreatedAt/UpdatedAt

---

.github/workflows/tests.yml

pop and fizz use complex test workflow so just keep them as is.

preparing go1.18 support (package specific workflow)

---

.gitignore
dialect_sqlite.go
dialect_sqlite_test.go

This PR allows to use `:memory:` and `mode=memory` in the `database.yml` configuration file to use SQLite in memory. This is something that comes very handy when dealing with SQLite based applications.
While on this I noticed there is the chance to support module-root relative routes in the `database.yml` and improve development experience for sqlite.

feature: supporting sqlite :memory: and mode=memory on the sqlite driver

---

connection.go
connection_test.go

Currently one can only use `conn.Store.TransactionContextOptions()` which means one does not get a connection that is part of the transaction.

feat: expose connection transactions with context and options

---

connection_instrumented.go

Fixes
```
panic: sql: Register called twice for driver instrumented-sql-driver-sqlite3 [recovered]
panic: sql: Register called twice for driver instrumented-sql-driver-sqlite3
goroutine 15 [running]:
testing.tRunner.func1.2({0x1837d40, 0xc000473b70})
/usr/lib/go/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
/usr/lib/go/src/testing/testing.go:1392 +0x5d2
panic({0x1837d40, 0xc000473b70})
/usr/lib/go/src/runtime/panic.go:844 +0x258
database/sql.Register({0x1a43574, 0x1f}, {0x1de6f60?, 0xc00046fb00})
/usr/lib/go/src/database/sql/sql.go:51 +0x1d4
github.com/gobuffalo/pop/v6.instrumentDriver(0xc0002e63c0, {0x1a1f3bd, 0x7})
/home/patrik/git/go/pkg/mod/github.com/gobuffalo/pop/v6@v6.0.1/connection_instrumented.go:68 +0x3e5
github.com/gobuffalo/pop/v6.openPotentiallyInstrumentedConnect …
```

fix: add lock to registering instrumented drivers

---

.github/workflows/tests.yml
pop.go
soda/cmd/root.go
soda/cmd/root_integration_test.go

Not fully sure if the issue happen again or if the previous patch does not fill all the cases. Anyway, the same issue happens again:
```console
$ soda reset -e test
pop v6.0.2
[POP] 2022/06/04 20:40:03 info - drop app_development (...)
Error: couldn't drop database app_development: error dropping...
```
Even though the `--env` (or short `-e`) flag is given, the command just follows the environment variable.
It seems like the issue was caused by confusing naming and the behavior of `PersistantPreRun` field of `cobra.Command` and `PersistentFlags()` function. I added a detailed comment on the code so easy to check later.
(One unrelated commit is also included :-)
Related: #282
Fixes #269

hotfix for ignored `--env` flag issue (#269)

---

connection.go
docker-compose.yml
executors_test.go

After a bit of code search I figured that the race detection mentioned in #723 is kind of a false positive. Adding this check ensures the race detector is not triggered.

fix: make disableEager not trigger the race detector

---

slices/map.go

Fixes https://github.com/gobuffalo/pop/issues/654

Make slices.Map UnmarshalJSON a pointer receiver

---

slices/map_test.go

added test cases for slices.Map (for #655, related to #654)

added test cases for slices.Map (for #655)

---

executors.go

When try to use `db.Eager().ValidateAndCreate(user)` to create a user and underlying `has_many` books, it succeeded for the first time when books table is empty, but failed to save the books in following creations.
Add where clause when check if the books exist as shown in the PR.
```go
exists, errE := Q(c).Where("id = ?", id).Exists(i)
```
```go
type User struct {
ID string `json:"id" db:"id"`
Name string `json:"name" db:"name"`
Books []Book `json:"books" has_many:"books" fk_id:"user_id"`
CreatedAt time.Time `json:"created_at" db:"created_at"`
UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}
type Book struct {
ID string `json:"id" db:"id"`
Name string `json:"name" db:"name"`
UserID string `json:"user_id" db:"user_id"`
User *User `json:"user" belongs_to:"users"`
CreatedAt …
```

fix eager creation for associations by adding where clause

---

.github/workflows/tests.yml
connection_details_test.go
database.yml
dialect_cockroach.go
dialect_cockroach_test.go
dialect_postgresql.go
dialect_postgresql_test.go
docker-compose.yml

Indeed, #402 is a valid and important issue that users can confuse.
* The `cd.URL` is a kind of raw value that should be able to directly interpreted by the underlying database engine, so using a plain version (without URL encoding) of the password with reserved characters is not a valid usage. However, when if the user provided a correctly encoded URL, we should be able to parse and store the value in CD structure.
* When we create URLs for database connection, we should be able to generate a correct URL with the parsed CD values, and it should be a valid URL that can be interpreted by the database engine.
* MySQL is an exception since their connection URL is not a standard format.
fixes #402

fixed url handling with reserved characters (fixes #402)

---

connection.go
connection_test.go

`Connection.Transaction()` starts a transaction before executing a given inner function and then commits or rollback the transaction controlled by the return error value of the inner function. However, as reported in #748, it just exits without committing or rolling back the current transaction so the transaction (and lock status) could remain as open (it could depend on the behavior of the backing database engine).
The current behavior of the method is:
```
=== RUN   Test_Connection_Transaction
[POP] 2022/09/22 20:08:51 sql - --- BEGIN Transaction ---
--- FAIL: Test_Connection_Transaction (0.00s)
panic: handler panic [recovered]
panic: handler panic
<...>
```
The fixed behavior by this PR is:
```
=== RUN   Test_Connection_Transaction
[POP] 2022/09/22 20:11:01 sql - --- BEGIN Transaction …
```

catch panic within transaction to complete rollback (fixes #748)

---

query.go
query_test.go

As reported in #524, `Where()` has a bug regarding regex handling for `IN` support.
This PR fixed the issue and improved test cases for `Where()`
fixes #778

fixed replacing bug on WHERE IN statement (fixes #778)

---

.github/workflows/tests.yml
dialect_mysql.go

PR #639 added an option `--column-statistics` for `mysqldump` but the option is new and is not supported by MySQL 5.7 (MySQL 5.7 is the oldest supported version) but it made the other users hard to work with. (see comments in #640)
see also: https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_column-statistics
fixes #640

removed mysqldump option `--column-statistics` to make it compatible with 5.7

---

connection.go
connection_test.go

As reported in #510, the `Connection.Close()` just closes the connection to the database but did not update the status of `Connection` so it could not be reused with `Open()`. 
This PR makes the method to reset `Store` so `Open()` can understand the status of the `Connection`. Also, added a test case for this issue.
fixes #510

fix Connection.Close() to reset the store

---

config.go
logger.go

The log should not be printed to the standard output. Standard output is for application.
fixes #768
related to #621, #622

made default logger to print output to stderr instead of stdout

---

schema_migrations.go

Made the 'version' column the primary key to fix #659.
The schema table does not strongly require a primary key itself, but having PK could be better, and the column `version` is actually a defacto primary key.
In the future, it could be better to consider #561 with it too.
fixes #659

made the 'version' column primary key to fix #659

---

dialect_mysql.go
query_test.go

Fixed  `Delete()` + `WHERE IN` issue on MySQL  for #699.
The direct cause was the implementation of `Delete()`. When the query could have `WHERE IN`, currently the query should be generated via SQLBuilder (specifically `sqlx.In()` in `sqlBuilder.compile()` to expand `?` to match with the arguments.
The root cause is the SQL syntax of MySQL. MySQL 5.7 does not support table alias for the `DELETE` statement, so `AS table_alias` causes a syntax error. I guess the `Delete()` for MySQL has its own implementation for this reason. The syntax was changed in 8.0 so when 5.7 is fully EOSed, we can use the generic version here.
fixes #699

fixed delete + where in issue on mysql (#699)

---

connection_details.go
dialect_cockroach.go
dialect_mysql.go
dialect_postgresql.go
dialect_sqlite.go

Indeed, the map `ConnectionDetails.Options` is not protected on write accesses. This PR adds a setter and getter for the map, and the setter uses a mutex lock to protect them. However, the CD operations only happen when the connection is defined and configured so I am not sure how they are accessed concurrently. :thinking: 
fixes #577

fixed concurrent map write issue on ConnectionDetails.Options (#577)

---

executors.go
query.go
query_test.go
sql_builder.go

Empty `Query` should not be executed.
fixes #560

prevent empty query to be executed

---

.github/workflows/release.yml
.goreleaser.yml
Makefile

It seems like the old token was expired. Also updated goreleaser version.

updated goreleaser configuration

---

slices/int.go
slices/int_test.go

Previously, Int.Scan() returned the non-empty slice '[0]' when reading an empty slice of ints from the database. This is a bug, as the output should also be empty. This patch fixes the bug and adds regression tests. Additionally, the code is updated to percolate up the errors from integer to string conversion, which was previously swallowed.

slices: update Int.Scan() to parse empty slices

---

slices/float.go
slices/float_test.go
slices_test.go

This bug is related to #791 and #788 but for `Float`. Copied the `Int` version and added an integration test for PostgreSQL.

fixed empty slice bug on slices.Float

---

connection.go
connection_test.go
logger.go

This PR makes `Transaction()` not swallow inner panic when rolling back inner panic to prevent connection leak. (followup for #748, #775)
fixes #793
With this configuration,
```go
app.GET("/panic", func(c buffalo.Context) error {
panic("panic message")
})
```
Previously we got a generic error but no information about the actual panic:
```
[POP] 2022/11/19 12:27:13 sql - BEGIN Transaction --- (conn=tx-2490861061155653040, tx=2490861061155653040)
[POP] 2022/11/19 12:27:13 sql - ROLLBACK Transaction (inner function panic) --- (conn=tx-2490861061155653040, tx=2490861061155653040)
ERRO[2022-11-19T12:27:13+09:00] transaction was rolled back due to inner panic conn=tx-2490861061155653040 db=0s params="{}" request_id=f3afa8520e74468e3126-605aa30f89aa98d921a6 status=500 tx=2490861061155653040 …
```

do not swallow panic when rolling back inner panic to prevent connection leak

---

database.yml
dialect.go
dialect_cockroach.go
dialect_common.go
dialect_mysql.go
dialect_postgresql.go
dialect_sqlite.go
executors.go
finders.go
logger.go

- Changed methods of the private interface `crudable` to pass `*Connection` instead of `store`
- This change will enable detailed log printing for `SQL` level of logs (connection ID, transaction ID, and pool statistics)
- Also addressed deadlock bug reported as #800
Sample Logs, when a TX is used:
```
[POP] 2022/12/16 23:44:16 sql - BEGIN Transaction --- (conn=tx-5581905573995530030, tx=5581905573995530030)
[POP] 2022/12/16 23:44:16 sql - INSERT INTO "users" ("created_at", "id", "name", "updated_at") VALUES (:created_at, :id, :name, :updated_at) | [{"id":"a1b61ca5-ba24-4ba4-b111-43e1d39e6bd0","name":"Username","created_at":"2022-12-16T23:44:16.653325+09:00","updated_at":"2022-12-16T23:44:16.653325+09:00"}] (conn=tx-5581905573995530030, tx=5581905573995530030)
[POP] 2022/12/16 23:44:16 sql …
```

made to pass connection instead of copying store

---

callbacks.go
callbacks_test.go
finders.go
pop_test.go
testdata/migrations/20181104135800_callbacks_users.up.fizz

See https://github.com/gobuffalo/pop/issues/557
Closes https://github.com/gobuffalo/pop/issues/476

Add `AfterEagerFind()`

---

callbacks.go

* readability improvement for exclusive blocks (follow up of #802)
* prevent unnecessary go routines by limiting them when only the model is `AfterFindable` (#799)
* Deep cascaded if blocks are not beautiful but sometimes easy to read. For this case, the exclusive condition is used for two blocks one by one, so grouping them with one if-else will make it easy to read.
* Unnecessary go routine creation was reported as #799 but did not addressed yet. The issue is reasonable, and also it looks better to read.
closes #799

prevent unnecessary go routines by limiting them when only the model is `AfterFindable`

---

dialect_cockroach.go
dialect_common.go
dialect_postgresql.go
dialect_sqlite.go
executors_test.go
model_context_test.go
query_test.go
store.go
tx.go

Using the `gen_random_uuid()` builtin can significantly speed up inserts because the primary key uniqueness constraint check is elided.
I've also fixed up code where there was a prepared statement being created for just one query, which is super inefficient.
I'm kinda having trouble running the tests locally, so I'd appreciate a workflow approval too. @aeneasr @sio4 👍

feat: use gen_random_uuid() for CockroachDB INSERTs

---

dialect_cockroach.go
dialect_postgresql.go
preload_associations.go

Issue: https://github.com/gobuffalo/pop/issues/812
The error handling when using `NamedQueryContext` was incorrect and would fail to return errors to the caller. In `preload_associatons.go` we didn't even close the rows 🤷 .

fix: incorrect error handling

---

file_migrator.go
migration_box.go

This PR solves the problem with migrations replacing all `?` with `$n` (rebinding arguments). Migrations currently use the `RawQuery` method, which replaces all instances of `?` as if it was running a Query. 
An example of where this becomes an issue, was brought up by @viktorkrepak in a Postgres migration:
```sql
CREATE DOMAIN http_url AS varchar(255) CONSTRAINT valid_url CHECK (VALUE ~ '^https?://[^\s/$.\?#][^\s]*$');
```
In this case, the `?` in the regex is replaced by `$1` and `$2`, breaking the regex.
- [RawQuery rebinds escaped characters](https://github.com/gobuffalo/pop/issues/567)
- [Allow escaping ? to use it for it's Postgres syntax.](https://github.com/gobuffalo/fizz/issues/72)
The solution is to call `Exec` on the connection directly vs `RawQuery`. I am not sure of the …

Migrations use Exec() directly vs RawQuery()
